laguage: generic 
sudo: required

services:
    - docker

before_install:
    - docker build -t cotizate/cotizate-app -f Dockerfile.dev .

script:
    - docker build -t cotizate/cotizte-app .
    - docker push cotizate/cotizate-app
