version: "3.7"

services:
    client:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - "/app/node_modules"
            - "./:/app"
