version: "3.7"

services:
    client:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        expose:
            - 9000
        volumes:
            - "/app/node_modules"
            - "./:/app"
    nginx:
        build: ./nginx
        ports:
            - 9000:9000
        depends_on:
            - client
