export const OBJETO_CATEGORIAS = 'OBJETO_CATEGORIAS'
export const FILTRO_CATEGORIAS = 'FILTRO_CATEGORIAS'
export const FILTRO_CATEGORIAS_ENTY = 'FILTRO_CATEGORIAS_ENTY'
export const FILTRO_CRITERIO_CATEGORIAS = 'FILTRO_CRITERIO_CATEGORIAS'
