export const DETALLE_PROYECTO = 'DETALLE_PROYECTO'
export const DETALLE_APORTES = 'DETALLE_APORTES'
export const DETALLE_FASES = 'DETALLE_FASES'
export const ERROR_DETALLE_PROYECTO = 'ERROR_DETALLE_PROYECTO'