export const SET_USER = 'SET_USER'
export const PROYECTOS_FINALIZADOS_LOAD = 'PROYECTOS_FINALIZADOS_LOAD'
export const PROYECTOS_DESTACADOS_LOAD = 'PROYECTOS_DESTACADOS_LOAD'
export const CAUSAS_SOCIALES_LOAD = 'CAUSAS_SOCIALES_LOAD'
